spring:
  config:
    import: classpath:secret.yml

  jpa:
    hibernate:
      ddl-auto: update

#    show-sql: true

  data:
    web:
      pageable:
        default-page-size: 10

logging:
  level:
    org.springframework.security: DEBUG
#    kea.dpang.order.feign.*: DEBUG

